[package]
name = "feattle"
version = "0.2.0"
authors = ["Guilherme Souza <sitegui@sitegui.com.br>"]
edition = "2018"
description = "Featture toggles for Rust, extensible and with background synchronization and administation UI"
repository = "https://github.com/sitegui/feattle-rs"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["toggle", "feature", "flag", "flipper"]
categories = ["config", "data-structures", "development-tools", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
use_uuid = ["feattle-core/uuid"]
use_warp = ["feattle-ui/warp"]

[dependencies]
feattle-core = { path = "../feattle-core" }
feattle-sync = { path = "../feattle-sync" }
feattle-ui = { path = "../feattle-ui" }

[dev-dependencies]
env_logger = "0.7.1"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
tokio = { version = "0.2.22", features = ["full"] }
uuid = "0.8.1"
warp = "0.2.4"

[[example]]
name = "gui"
path = "examples/gui.rs"
required-features = ["use_uuid", "use_warp"]