[package]
name = "feattle"
version = "0.1.0"
authors = ["Guilherme Souza <19gui94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
feattle-core = { path = "../feattle-core" }
feattle-sync = { path = "../feattle-sync" }

[dev-dependencies]
uuid = "0.8.1"
strum = "0.19.2"