[package]
name = "feattle"
version = "0.1.0"
authors = ["Guilherme Souza <19gui94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
use_uuid = ["feattle-core/use_uuid"]

[dependencies]
feattle-core = { path = "../feattle-core" }
feattle-sync = { path = "../feattle-sync" }
feattle-ui = { path = "../feattle-ui" }

[dev-dependencies]
env_logger = "0.7.1"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
strum = "0.19.2"
tokio = { version = "0.2.22", features = ["full"] }
uuid = "0.8.1"
warp = "0.2.4"

[[example]]
name = "gui"
path = "examples/gui.rs"
required-features = ["use_uuid"]