[package]
name = "feattle-ui"
version = "0.1.0"
authors = ["Guilherme Souza <19gui94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
feattle-core = { path = "../feattle-core" }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
warp = "0.2.4"