[package]
name = "feattle-sync"
version = "0.1.0"
authors = ["Guilherme Souza <19gui94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
feattle-core = { path = "../feattle-core" }
log = "0.4.11"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"